name: proj_job_test01
description: ''
version: 0.0.1
author: sharad.ghallal@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projjobtest01
  parentArtefactID: sharadghallalcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-31 07:55:40'
pipelines:
  pipelines/pl_job_test01:
    name: pl_job_test01
    description: job first pipeline
    author: sharad.ghallal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-31 07:55:40'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pl_job_test02:
    name: pl_job_test02
    description: job second pipeline
    author: sharad.ghallal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-31 07:56:12'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/job_testing:
    name: job_testing
    description: ''
    fabricUID: 13085
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pl_job_test01
    - pipelines/pl_job_test02
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-05-31 08:01:48'
    author: sharad.ghallal@cloudaeon.net
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-31 07:55:40'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-31T07:55:40.085202Z'
  name: plibMaven
  version: 7.1.102
  id: '535140871'
  createdAt: '2024-05-31T07:55:40.085202Z'
  type: plibMaven
- modifiedAt: '2024-05-31T07:55:40.085202Z'
  name: plibPypi
  version: 1.8.19
  id: '105334232'
  createdAt: '2024-05-31T07:55:40.085202Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-31 07:54:50'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-31 07:54:50'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
